version: '3'
services:
  db2:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_creator_node
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
    ports:
      - '4442:5432'
  redis2:
    image: redis:5.0.4
    ports:
      - '4389:6379'

volumes:
  postgres_data2:
