version: '3'
services:
  creator-node:
    network_mode: "host"
    build: ../.
    env_file:
      - ./development.env
    volumes:
      - file_storage:/file_storage

volumes:
  ipfs_data:
  file_storage:
