version: '3'
services:
  db:
    network_mode: "host"
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_discovery
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis-server:
    network_mode: "host"
    image: redis:3.0-alpine
    command: redis-server --save '' 

volumes:
  postgres_data:
