# Depends on the docker-compose.base.yml file for db, redis-server and ipfs-node processes

version: '3'
services:
  celery-worker:
    network_mode: "host"
    build: .
    restart: always
    command: sh -c '/wait && exec celery -A src.worker.celery worker'
    env_file:
      - .env
    depends_on:
      - db
      - redis-server
  celery-beat:
    network_mode: "host"
    build: . 
    restart: always
    command: sh -c '/wait && exec celery -A src.worker.celery beat'
    env_file:
      - .env
    depends_on:
      - celery-worker
  web-server:
    network_mode: "host"
    build: .
    restart: always
    command: sh -c '/wait && exec ./scripts/dev-server.sh'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - '.:/audius-discovery-provider'
