version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_content_service
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '8432:5432'
  content-service:
    build: ../.
    env_file:
      - ./development.env
    depends_on:
      - db
    ports:
      - '8000:8000'

volumes:
  postgres_data:
