version: '3'
services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: audius_creator_node
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '4432:5432'
  redis:
    image: redis:5.0.4
    ports:
      - '4379:6379'

volumes:
  postgres_data:
